server:
  port: ${PORT:8080}
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:pradeep
    username: sa
    password:
    driverClassName: org.h2.Driver
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  application:
    name: signup-service

eureka:
  instance:
   leaseRenewalIntervalInSeconds: 1
   leaseExpirationDurationInSeconds: 3
  client:
   serviceUrl:
    defaultZone : http://localhost:8087/eureka     
info:
 app:
  name: sigup-service 